#spring.jpa.defer-datasource-initialization=true
#The above is n

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  kafka:
#    producer:
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 8095
